POST http://localhost:8000/tasks
Content-Type: application/json

{
    "task_name": "Играть 8 часов в кс",
    "task_description": "В доту",
    "deadline": "Целый день",
    "email": "krakhimov.it@gmial.com"
}

###

GET http://localhost:8000/tasks

###

DELETE http://localhost:8000/tasks

###
GET http://localhost:8000/tasks/5fd77d20b957322dbce4bb60
